about/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^info/$', info, name='info'),
    url(r'^branch/$', branch, name='branch'),
    url(r'^business/$', business, name='business'),
    url(r'^culture/$', culture, name='culture'),
]

resume/urls.py
from django.conf.urls import url
from .views import send_resume, resume_detail

urlpatterns = [
    url(r'^send_resume/(?P<id>\d+)/$', send_resume, name='send_resume'),
    url(r'^resume_detail/(?P<id>\d+)/$', resume_detail, name='resume_detail')
]

tencentHR/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('zhaopin.urls', namespace='zhaopin')),
    url(r'^about/', include('about.urls', namespace='about')),
    url(r'^inTencent/', include('inTencent.urls', namespace='inTencent')),
    # url(r'^search/',include('haystack.urls')),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^users/',include('django.contrib.auth.urls')),
    url(r'^resume/',include('resume.urls',namespace='resume'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.conf.urls import url
from .views import (register_can, register_rec, login_can, login_rec, logout,
                    edit_info_cand, edit_resume_cand, edit_info_rec, resume_list,
                    send_zhaopin_list, zhaopin_detail)
from .chart import histogram, line

urlpatterns = [
    url(r'^register_can/$', register_can, name='register_can'),
    url(r'^register_rec/$', register_rec, name='register_rec'),
    url(r'^login_can/$', login_can, name='login_can'),
    url(r'^login_rec/$', login_rec, name='login_rec'),
    url(r'^logout/$', logout, name='logout'),
    url(r'^edit_info_cand/(?P<id>\d+)/$', edit_info_cand, name='edit_info_cand'),
    url(r'^edit_resume_cand/(?P<id>\d+)/$', edit_resume_cand, name='edit_resume_cand'),
    url(r'^edit_info_rec/(?P<id>\d+)/$', edit_info_rec, name='edit_info_rec'),
    url(r'^resume_list/$', resume_list, name='resume_list'),
    url(r'^zhaopin_list/$', send_zhaopin_list, name='send_zhaopin_list'),
    url(r'^zhaopin_detail/(?P<id>\d+)/$', zhaopin_detail, name='zhaopin_detail'),

    url(r'^histogram/$', histogram, name='histogram'),
    url(r'^line/$', line, name='line'),
]

zhaopin/urls.py
from django.conf.urls import url
from .views import (index, detail, social, SearchView, add_zhaopin,)

urlpatterns = [
    url(r'^index/$', index, name='index'),
    url(r'^detail/(?P<pk>\d+)/$', detail, name='detail'),
    url(r'^social/$', social, name='social'),
    url(r'^search/$', SearchView.as_view(), name='search'),
    url(r'^add_zhaopin', add_zhaopin, name='add_zhaopin'),

]

users/models.py
from django.db import models
from django.contrib.auth.hashers import make_password, check_password


# Create your models here.
class Candidaters(models.Model):
    username = models.CharField(max_length=20, verbose_name='用户名')
    password1 = models.CharField(max_length=128, verbose_name='密码')
    password2 = models.CharField(max_length=128, verbose_name='密码确认')
    tel = models.CharField(max_length=20, verbose_name='手机')
    email = models.EmailField(verbose_name='邮箱')
    headshot = models.ImageField(upload_to='avatar/%Y/%m/%d', default='default.jpg',
                                 verbose_name='头像', null=True, blank=True)

    def __str__(self):
        return self.username

    def save(self, *args, **kwargs):
        self.password1 = self.password2 = set_password(self.password1)
        super(Candidaters, self).save(*args, **kwargs)


class Recruiter(models.Model):
    username = models.CharField(max_length=20, verbose_name='用户名')
    password1 = models.CharField(max_length=128, verbose_name='密码')
    password2 = models.CharField(max_length=128, verbose_name='密码确认')
    tel = models.CharField(max_length=20, verbose_name='手机')
    email = models.EmailField(verbose_name='邮箱')
    department = models.CharField(max_length=30, verbose_name='部门', null=True, blank=True)

    def __str__(self):
        return self.username

    def save(self, *args, **kwargs):
        self.password1 = self.password2 = set_password(self.password1)
        super(Recruiter, self).save(*args, **kwargs)


def set_password(password):
    # 设置密码
    password_hash = make_password(password)
    return password_hash


def check_password_hash(password, password_hash):
    return check_password(password, password_hash)

users/forms.py
from .models import Candidaters, Recruiter
from django import forms
from resume.models import Resume


class CanRegisterForm(forms.ModelForm):
    class Meta:
        model = Candidaters
        fields = '__all__'

        css = {'class': "longinput3 changeCheck", 'size': "35", 'maxlength': "60"}
        widgets = {
            'username': forms.TextInput(attrs=css),
            'password1': forms.PasswordInput(attrs=css),
            'password2': forms.PasswordInput(attrs=css),
            'headshot': forms.FileInput(attrs=css),
            'email': forms.EmailInput(attrs=css),
            'tel': forms.TextInput(attrs=css),
        }


class RecRegisterForm(forms.ModelForm):
    class Meta:
        model = Recruiter
        fields = '__all__'

        css = {'class': "longinput3 changeCheck", 'size': "35", 'maxlength': "60"}
        widgets = {
            'username': forms.TextInput(attrs=css),
            'password1': forms.PasswordInput(attrs=css),
            'password2': forms.PasswordInput(attrs=css),
            'department': forms.TextInput(attrs=css),
            'email': forms.EmailInput(attrs=css),
            'tel': forms.TextInput(attrs=css),
        }


class ResumeForm(forms.ModelForm):
    class Meta:
        model = Resume
        fields = ['name', 'age', 'sex', 'address', 'school', 'experience', 'evaluation']

users/views.py
from django.shortcuts import render, HttpResponse, redirect, reverse
from django.http import HttpResponseRedirect

from users import models
from .forms import RecRegisterForm, CanRegisterForm
from django.contrib import messages
from .models import Recruiter, Candidaters
from .models import set_password, check_password_hash
from resume.forms import ResumeForm
from resume.models import Resume, Resume_relationship
from zhaopin.models import Zhaopin


# Create your views here.


def register_can(request):
    if request.method == 'POST':
        form = CanRegisterForm(request.POST, request.FILES)
        # 数据提交是否合法
        if form.is_valid():
            username = form.cleaned_data['username']
            # 用户名已存在,返回注册页面
            if len(Candidaters.objects.filter(username=username)) != 0:
                # messages.info(request, '用户名已存在!')
                info = {'error': '用户名已存在!'}
                return render(request, 'users/register.html', info)
            else:
                password1 = form.cleaned_data['password1']
                password2 = form.cleaned_data['password2']
                if password1 != password2:
                    # messages.info(request, '两次密码输入不一致!')
                    info = {'error': '两次密码输入不一致!'}
                    return render(request, 'users/register.html', info)
                else:
                    # 加密放在了model里进行操作
                    form.save()
                    messages.success(request, '注册成功!')
                    return HttpResponseRedirect('/index')
    else:
        form = CanRegisterForm()
    return render(request, 'users/register.html', locals())


def register_rec(request):
    if request.method == 'POST':
        form = RecRegisterForm(request.POST, request.FILES)
        # 数据提交是否合法
        if form.is_valid():
            username = form.cleaned_data['username']
            # 用户名已存在,返回注册页面
            if len(Recruiter.objects.filter(username=username)) != 0:
                messages.error(request, '用户名已存在!')
                return render(request, 'users/register.html', locals())
            else:
                password1 = form.cleaned_data['password1']
                password2 = form.cleaned_data['password2']
                if password1 != password2:
                    messages.error(request, '两次密码输入不一致!')
                    return render(request, 'users/register.html', locals())
                else:
                    # 加密放在了model里进行操作
                    form.save()
                    messages.success(request, '注册成功!')
                    return HttpResponseRedirect('/index')
    else:
        form = RecRegisterForm()
    return render(request, 'users/register.html', locals())


def login_can(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        # 检查用户是否存在
        cand = Candidaters.objects.filter(username=username).first()
        # 用户不存在
        if cand == None:
            messages.error(request, '用户名或密码错误!')
            return render(request, 'users/login_cand.html', locals())
        password1 = cand.password1
        # 校验密码是否正确
        # 密码错误
        if not check_password_hash(password, password1):
            messages.error(request, '用户名或密码错误!')
            return render(request, 'users/login_cand.html', locals())

        request.session['username'] = cand.username
        request.session['id'] = cand.id
        request.session['mark'] = 0
        messages.success(request, '登录成功!')
        return HttpResponseRedirect('/index')
    return render(request, 'users/login_cand.html', locals())


def login_rec(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        department = request.POST.get('department')

        # 检查用户是否存在
        rec = Recruiter.objects.filter(username=username).first()
        # 用户不存在
        if rec == None:
            messages.error(request, '用户名或密码错误!')
            return render(request, 'users/login_rec.html', locals())
        password1 = rec.password1
        # 校验密码是否正确
        # 密码错误
        if not check_password_hash(password, password1):
            messages.error(request, '用户名或密码错误!')
            return render(request, 'users/login_rec.html', locals())
        # 部门名不正确
        if department != rec.department:
            messages.error(request, '用户名或密码错误!')
            return render(request, 'users/login_rec.html', locals())
        request.session['username'] = rec.username
        request.session['id'] = rec.id
        request.session['mark'] = 1
        messages.success(request, '登录成功!')
        return HttpResponseRedirect('/index')
    return render(request, 'users/login_rec.html', locals())


def logout(request):
    request.session.flush()
    return redirect(reverse('zhaopin:index'))


def edit_info_cand(request, id):
    cand = Candidaters.objects.get(id=id)
    if request.method == 'POST':
        username = request.POST.get('username')
        email = request.POST.get('email')
        tel = request.POST.get('tel')
        headshot = request.FILES.get('headshot') or 'default.jpg'
        models.Candidaters.objects.filter(id=id).update(username=username,
                                                        email=email, headshot=headshot, tel=tel)
        # info = {'message': '修改成功!'}
        messages.success(request, '修改成功!')
        return HttpResponseRedirect('/users/edit_info_cand/%s' % id, )
    return render(request, 'candidaters/can_info_edit.html', locals())


def edit_resume_cand(request, id):
    resume = Resume.objects.filter(user_id=id).first()
    if request.method == 'POST':
        form = ResumeForm(request.POST, instance=resume)
        if form.is_valid():
            try:
                # 修改简历
                form.save()
                messages.success(request, '简历修改成功!')
            except:
                # 创建简历
                form.cleaned_data['user_id'] = int(id)
                Resume.objects.create(**form.cleaned_data)
                messages.success(request, '简历创建成功!')
    else:
        form = ResumeForm(instance=resume)
    return render(request, 'candidaters/can_resume_edit.html', locals())


def edit_info_rec(request, id):
    rec = Recruiter.objects.get(id=id)
    if request.method == 'POST':
        username = request.POST.get('username')
        email = request.POST.get('email')
        tel = request.POST.get('tel')
        department = request.POST.get('department')
        models.Recruiter.objects.filter(id=id).update(username=username,
                                                      email=email, department=department, tel=tel)
        messages.success(request, '修改成功!')
        return HttpResponseRedirect('/users/edit_info_rec/%s' % id, )
    return render(request, 'recruiter/rec_info_edit.html', locals())


def resume_list(request):
    try:
        rec_id = int(request.session['id'])
        resume_id_list = Resume_relationship.objects.filter(rec_id=rec_id)
        resume_list = [Resume.objects.filter(id=resume_id.resume_id)[0] for resume_id in resume_id_list]
        # 去重
        resume_list = set(resume_list)
    except:
        info = '暂无投递简历!'
    return render(request, 'recruiter/rec_resume_list.html', locals())


# 已投递的招聘岗位
def send_zhaopin_list(request):
    try:
        # 候选人id
        cand_id = int(request.session['id'])
        # 候选人对应简历
        resume = Resume.objects.filter(user_id=cand_id).first()
        # 候选人投递的岗位
        zhaopin_id_list = Resume_relationship.objects.filter(resume_id=resume.id)
        zhaopin_list = [Zhaopin.objects.filter(id=zhaopin_id.zhaopin_id)[0] for zhaopin_id in zhaopin_id_list]
    except:
        info = '还未投递简历,赶紧去看看吧'
    return render(request, 'candidaters/send_zhaopin_list.html', locals())


def zhaopin_detail(request, id):
    return HttpResponseRedirect('/detail/%s/' % id)

users/templates/recruiter/base_rec.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block head %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static 'ui/themes/default/easyui.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'ui/themes/icon.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'ui/demo/demo.css' %}">
    <script type="text/javascript" src="{% static 'ui/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'ui/jquery.easyui.min.js' %}"></script>
    <link rel="shortcut icon" href="{% static 'base/images/logo.png' %}">
    <link href="{% static 'admin/bower_components/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'admin/bower_components/metisMenu/dist/metisMenu.min.css' %}" rel="stylesheet">
    <link href="{% static 'admin/dist/css/sb-admin-2.css' %}" rel="stylesheet">
    <link href="{% static 'admin/bower_components/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet"
          type="text/css">
    <link href="{% static 'admin/css/common.css' %}" type="text/css" rel="stylesheet">
    <style>
        .page-header {
            margin: 12px;
        }
    </style>
    {% block tilte %}
        <title>个人信息 | 社会招聘 | Tencent 腾讯招聘</title>
    {% endblock %}
{% endblock %}
<body>
{% block content %}
    <div id="wrapper">
    <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">下拉菜单</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="navbar-default sidebar" role="navigation">
            <div class="sidebar-nav navbar-collapse">
                <ul class="nav" id="side-menu">
                    <li>
                        <a href="#"><i class="fa fa-tag" aria-hidden="true"></i> 招聘管理<span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a href="{% url 'zhaopin:add_zhaopin' %}"><i class="fa fa-list" aria-hidden="true"></i> 发布岗位</a>
                            </li>
                            <li>
                                <a href="{% url 'users:resume_list' %}"><i class="fa fa-bolt" aria-hidden="true"></i> 简历管理</a>
                            </li>
                            <li>
                                <a href="{% url 'users:edit_info_rec' request.session.id %}"><i class="fa fa-user" aria-hidden="true"></i> 个人信息</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-file-text" aria-hidden="true"></i> 数据统计<span
                                class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a href="{% url 'users:histogram'%}"><i class="fa fa-filter" aria-hidden="true"></i>岗位类别统计</a>
                            </li>
                            <li>
                                <a href="{% url 'users:line' %}"><i class="fa fa-filter" aria-hidden="true"></i> 岗位数量统计</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
{% endblock %}
</div>

{% block js %}
    <script src="{% static 'admin/bower_components/jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'admin/bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'admin/bower_components/metisMenu/dist/metisMenu.min.js' %}"></script>
    <script src="{% static 'admin/dist/js/sb-admin-2.js' %}"></script>

    <script type="text/javascript" src="{% static 'admin/ueditor/ueditor.config.js' %}"></script>
    <script type="text/javascript" src="{% static 'admin/ueditor/ueditor.all.js' %}"></script>
    <script type="text/javascript" src="{% static 'admin/ueditor/lang/zh-cn/zh-cn.js' %}"></script>
{% endblock %}

</body>

users/templates/recruiter/rec_lines.html
{% extends "recruiter/base_rec.html" %}

{% load staticfiles %}
{% block content %}
    {{ block.super }}
    <script src="{% static 'hchart/highcharts.js' %}"></script>
    <script src="{% static 'hchart/modules/exporting.js' %}"></script>

    <div id="page-wrapper">

        <div class="row">
            <div class="col-lg-12">
                <h3 class="page-header">线性统计</h3>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">


                <div id="container">

                </div>

                <script>
                    var chart = Highcharts.chart('container', {
                        chart: {
                            type: 'line'
                        },
                        title: {
                            text: '岗位发布数量线性图'
                        },
                        subtitle: {
                            text: ''
                        },
                        xAxis: {
                            categories: {{ categories|safe }}
                        },
                        yAxis: {
                            title: {
                                text: '岗位数量(个)'
                            }
                        },
                        plotOptions: {
                            line: {
                                dataLabels: {
                                    enabled: true          // 开启数据标签
                                },
                                enableMouseTracking: false // 关闭鼠标跟踪，对应的提示框、点击事件会失效
                            }
                        },
                        series:[{{ series |safe }}]
                    });
                </script>


            </div>
        </div>


    </div>
{% endblock %}

users/templates/recruiter/rec_resume_list.html
{% extends "recruiter/base_rec.html" %}

{% block content %}
    {{ block.super }}
    <div id="page-wrapper">
        <div class="row">
            <div class="col-lg-12">
                <h3 class="page-header">简历管理/简历列表</h3>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        简历列表
                    </div>
                    <div class="panel-body">
                        <div class="col-md-12" id="key_search">
                            <div class="col-lg-6">
                            </div>
                        </div>
                        <table class="table table-bordered">
                            <tr class="text-primary" style="font-weight:bold;">
                                <td style="width:10%">姓名</td>
                                <td style="width:18%">性别</td>
                                <td style="width:18%">年龄</td>
                                <td style="width:18%">学校</td>
                                {#                                <td style="width:18%">投递时间</td>#}
                                <td style="width:18%">操作</td>
                            </tr>
                            {% if resume_list %}
                                {% for resume in resume_list %}
                                    <tr>
                                        <td>{{ resume.name }}</td>
                                        <td>{% if resume.sex == 0 %}女{% else %}男{% endif %}</td>
                                        <td>{{ resume.age }}</td>
                                        <td>{{ resume.school }}</td>
                                        {#                                    <td>{{ 投递时间 }}</td>#}
                                        <td>
                                            <a href="{% url 'resume:resume_detail' resume.id %}">查看</a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            {% else %}
                                <tr>
                                    <h4>{{ info }}</h4>
                                </tr>
                            {% endif %}
                        </table>


                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}

    <script>
        $(document).ready(function () {
            $("#btn-search").click(function () {
                var key = $("#key").val();
                location.href = "{{ url }}?page=1&key=" + key;
            });
        });

    </script>

{% endblock %}

users/templates/recruiter/rec_statics.html
{% extends "recruiter/base_rec.html" %}
{% load staticfiles %}
{% block head %}
    {{ block.super }}
{% endblock %}
{% block content %}
    {{ block.super }}
    <script src="{% static 'hchart/highcharts.js' %}"></script>
    <script src="{% static 'hchart/modules/exporting.js' %}"></script>

    <div id="page-wrapper">

        <div class="row">
            <div class="col-lg-12">
                <h3 class="page-header">统计图表</h3>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">

                <div id="container"></div>
                <script>
                    $(function () {
                        var chart = Highcharts.chart('container', {
                            title: {
                                text: '招聘岗位分类统计'
                            },
                            subtitle: {
                                text: []
                            },
                            xAxis: {
                                categories: {{ Categories |safe }}
                            },
                            series: [{{ data |safe }}]
                        });
                    });
                </script>

            </div>
        </div>


    </div>
{% endblock %}

users/templates/recruiter/resume_detail.html
{% extends "recruiter/base_rec.html" %}

{% block content %}
    {{ block.super }}
    <div id="reg0" class="maxwidth">
        <div class="box wcont_a">
            <div class="blueline">
            </div>
            <br>
            <div id="frm_reg1" name="frm_reg1">
                <input id="type" type="hidden" name="type" value="0"/>
                <div id="reg_content" class="regtitlebg">
                    <div class="regtitle">个人简历</div>
                    <br>
                    <form action="{% url 'users:edit_resume_cand' request.session.id %}" method="post"
                          enctype="multipart/form-data">
                        {% csrf_token %}
                        <table class="reg" cellpadding="0" cellspacing="0">
                            {% for field in form %}
                                <tr>
                                    <td class="k row2in1" valign="top">
                                        {{ field.label_tag }}
                                    </td>
                                    <td>
                                        {{ field }}<br>
                                    </td>
                                    <td>
                                        {{ field.errors }}
                                    </td>
                                    <td>
                                        {% if field.help_text %}
                                            <p class="help text-small text-muted">{{ field.help_text|safe }}</p>
                                        {% endif %}
                                    </td>
                                </tr>
                            {% endfor %}
{#                            <tr>#}
{#                                <td></td>#}
{#                                <td>#}
{#                                    <div class="height20"></div>#}
{#                                    <input type="submit" class="but4" id="btnSubmit" value="确　定">#}
{#                                </td>#}
{#                            </tr>#}
                        </table>
                    </form>
                </div>
                <br>
            </div>
        </div>
    </div>

{% endblock %}
{% block js %}
    <script src="//cdn.bootcss.com/holder/2.9.4/holder.min.js"></script>


    <script>
        var ue = UE.getEditor('input_content', {
            initialFrameWidth: "100%",
            initialFrameHeight: "300",
        });
    </script>
    <script>
        $(document).ready(function () {
            var img;

            function getCookie(name) {
                var r = document.cookie.match("\\b" + name + "=([^;]*)\\b");
                return r ? r[1] : undefined;
            }

            $("#btn-upload").click(function () {
                var img = $("#upload_img")[0].files[0];
                var formData = new FormData();
                formData.append("img", img);
                $.ajax({
                    url: "/upload",
                    type: "POST",
                    dataType: "json",
                    cache: false,
                    contentType: false,
                    processData: false,
                    data: formData,
                    success: function (re) {
                        if (re.ok == 1) {
                            $("#show_img").attr("src", "/static/" + re.img);
                            img = re.img;
                            $("#input_img").attr("value", img);
                        }
                    }
                });
            });
            $("#btn-sub").click(function () {
                var title = $("#input_title").val();
                var info = $("#input_info").val();
                var _xsrf = getCookie("_xsrf");
                var content = UE.getEditor('input_content').getContent();
                var tag = $("#input_tag").val();
                var id = $("#input_id").val();
                var img = $("#input_img").val();
                var data = {
                    "title": title, "info": info,
                    "content": content, "tag": tag,
                    "img": img, "id": id,
                    "_xsrf": _xsrf
                };
                $.ajax({
                    url: "/art/art_ed_post",
                    type: "POST",
                    data: data,
                    dataType: "json",
                    success: function (re) {
                        if (re.ok == 1) {
                            location.href = "/art/art_list";
                        } else {
                            var fields = ["title", "info", "content", "tag", "img"];
                            for (v in fields) {
                                if (typeof re[fields[v]] == "undefined") {
                                    $("#error_" + fields[v]).empty();
                                } else {
                                    $("#error_" + fields[v]).empty();
                                    $("#error_" + fields[v]).append("<font style='color:red'>" + re[fields[v]] + "</font>");
                                }
                            }
                        }
                    }
                });
            });
        });
    </script>
{% endblock %}