about/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^info/$', info, name='info'),
    url(r'^branch/$', branch, name='branch'),
    url(r'^business/$', business, name='business'),
    url(r'^culture/$', culture, name='culture'),
]

resume/urls.py
from django.conf.urls import url
from .views import send_resume, resume_detail

urlpatterns = [
    url(r'^send_resume/(?P<id>\d+)/$', send_resume, name='send_resume'),
    url(r'^resume_detail/(?P<id>\d+)/$', resume_detail, name='resume_detail')
]

tencentHR/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('zhaopin.urls', namespace='zhaopin')),
    url(r'^about/', include('about.urls', namespace='about')),
    url(r'^inTencent/', include('inTencent.urls', namespace='inTencent')),
    # url(r'^search/',include('haystack.urls')),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^users/',include('django.contrib.auth.urls')),
    url(r'^resume/',include('resume.urls',namespace='resume'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

zhaopin/urls.py
from django.conf.urls import url
from .views import (index, detail, social, SearchView, add_zhaopin,)

urlpatterns = [
    url(r'^index/$', index, name='index'),
    url(r'^detail/(?P<pk>\d+)/$', detail, name='detail'),
    url(r'^social/$', social, name='social'),
    url(r'^search/$', SearchView.as_view(), name='search'),
    url(r'^add_zhaopin', add_zhaopin, name='add_zhaopin'),

]

zhaopin/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class WorkLocation(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Zhaopin(models.Model):
    title = models.CharField(max_length=50, verbose_name='标题')
    content = models.TextField(verbose_name='招聘要求')
    peopleNumber = models.IntegerField(verbose_name='人数')
    workLocation = models.ForeignKey(WorkLocation, verbose_name='工作地点')
    publishTime = models.DateField(auto_now_add=True, verbose_name='创建时间')
    category = models.ForeignKey(Category, verbose_name='类别')
    author = models.ForeignKey('users.Recruiter', verbose_name='作者', default='管理员')

    def __str__(self):
        return self.title

zhaopin/forms.py
from django.forms import ModelForm
from .models import Zhaopin


class add_zhaopinForm(ModelForm):
    class Meta:
        model = Zhaopin
        fields = ['title', 'workLocation', 'peopleNumber', 'category', 'content']

zhaopin/views.py
from django.db.models import Q
from django.shortcuts import render, redirect, reverse
from django.http import HttpResponse
from .models import Zhaopin, Category, WorkLocation
from utils import custom_paginator
from django.views.generic import ListView
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from users.models import Candidaters, Recruiter
from .forms import add_zhaopinForm
from django.contrib import messages


# Create your views here.

def index(request):
    try:
        mark = int(request.session['mark'])
    except:
        mark = None
        # 求职者
    if mark == 0:
        u_id = request.session.get('id')
        cand = Candidaters.objects.get(id=u_id)
        # 招聘
    if mark == 1:
        u_id = request.session.get('id')
        rec = Recruiter.objects.get(id=u_id)

    keywords = request.GET.get('keywords')
    zhaopin_list = Zhaopin.objects.all().order_by('-publishTime')[:10]
    category_list = Category.objects.all()
    workLocation_list = WorkLocation.objects.all()
    if not keywords:
        keywords = ''
    return render(request, 'index.html', locals())


def detail(request, pk):
    category_list = Category.objects.filter(~Q(name=''))
    workLocation_list = WorkLocation.objects.all()
    workLocation_list1 = workLocation_list[:9]
    workLocation_list2 = workLocation_list[9:]

    zhaopin = Zhaopin.objects.get(pk=pk)
    job_content_list = zhaopin.content.split('\n')
    return render(request, 'zhaopin/detail.html', locals())


def social(request):
    zhaopin_list = Zhaopin.objects.all().order_by('-publishTime')[:10]
    zhaopin_list1 = zhaopin_list[:5]
    zhaopin_list2 = zhaopin_list[5:10]
    workLocation_list = WorkLocation.objects.all()
    category_list = Category.objects.filter(~Q(name=''))
    return render(request, 'zhaopin/social.html', locals())


class SearchView(ListView):
    model = Zhaopin
    template_name = 'zhaopin/search.html'
    context_object_name = 'zhaopin_list'

    def get_queryset(self):
        keywords = self.request.GET.get('keywords') or ''
        workLocation_id = self.request.GET.get('lid') or 0
        category_id = self.request.GET.get('tid') or 0

        workLocation_id = int(workLocation_id)
        category_id = int(category_id)

        # 搜索关键词
        if keywords and not workLocation_id and not category_id:
            zhaopin_list = super().get_queryset().filter(
                (Q(title__contains=keywords) | Q(content__contains=keywords))
            ).order_by('-publishTime')
        # 工作地筛选
        elif workLocation_id and not category_id:
            zhaopin_list = super().get_queryset().filter(workLocation_id=workLocation_id).order_by('-publishTime')
        # 职位分类筛选
        elif category_id and not workLocation_id:
            zhaopin_list = super().get_queryset().filter(category_id=category_id).order_by('-publishTime')
        # 工作地/职位分类一起筛选
        elif workLocation_id and category_id:
            zhaopin_list = super().get_queryset().filter(
                Q(workLocation_id=workLocation_id) & Q(category_id=category_id)).order_by(
                '-publishTime')
        # 工作地/职位分类/关键词一起筛选
        elif keywords and workLocation_id and category_id:
            zhaopin_list = super().get_queryset().filter(
                (Q(title__contains=keywords) | Q(content__contains=keywords)) & Q(workLocation_id=workLocation_id) & Q(
                    category_id=category_id)
            ).order_by('-publishTime')
        # 无条件搜索
        else:
            zhaopin_list = super().get_queryset().all().order_by('-publishTime')

        self.zhaopin_list = zhaopin_list
        self.workLocation_id = workLocation_id
        self.category_id = category_id
        self.keywords = keywords
        return self.zhaopin_list, self.workLocation_id, self.category_id, self.keywords

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        paginator = Paginator(self.zhaopin_list, 10)
        page = self.request.GET.get('page', 1)
        page_range = paginator.page_range
        zhaopin_list = paginator.page(page)
        list_num = paginator.count

        start, end = custom_paginator(int(page), len(page_range), 10)
        page_range = range(start, end + 1)
        # 获取所有的工作地和分类
        category_list = Category.objects.filter(~Q(name=''))
        workLocation_list = WorkLocation.objects.all()
        workLocation_list1 = workLocation_list[:9]
        workLocation_list2 = workLocation_list[9:]

        context.update({
            'list_num': list_num,
            'page_range': page_range,
            'zhaopin_list': zhaopin_list,
            'workLocation_id': self.workLocation_id,
            'category_id': self.category_id,
            'keywords': self.keywords,
            'category_list': category_list,
            'workLocation_list1': workLocation_list1,
            'workLocation_list2': workLocation_list2
        })
        return context


def add_zhaopin(request):
    if request.method == 'POST':
        form = add_zhaopinForm(request.POST)
        if form.is_valid():
            author_id = request.session['id']
            form.cleaned_data['author_id'] = author_id
            Zhaopin.objects.create(**form.cleaned_data)
            messages.success(request, '招聘岗位发布成功!')
            return redirect(reverse('zhaopin:add_zhaopin'))
    else:
        form = add_zhaopinForm()
        return render(request, 'zhaopin/add_zhaopin.html', locals())

zhaopin/templates/zhaopin/detail.html
{% extends 'base.html' %}


{% block tilte %}
    <title>{{ zhaopin }} | 社会招聘 | Tencent 腾讯招聘</title>
{% endblock %}
<body>
{% block content %}
    <div id="bread">
        <a href="{% url 'zhaopin:social' %}">社会招聘</a><span>&nbsp;</span><a
            href="{% url 'zhaopin:search' %}">职位搜索</a><span>&nbsp;</span>{{ zhaopin.title }}
    </div>
    <div id="position_detail" class="maxwidth">
        <div class="box wcont_a">
            <div class="blueline">
                <div class="butzwss left"></div>
                <div class="clr"></div>
            </div>
            <form action="{% url 'zhaopin:search' %}" id="searchform" class="buts1">
                <div id="searchrow1">
                    <div id="search1"><input id="search2" name="keywords" placeholder="请输入关键词" value="{{ keywords }}"
                                             class="left"/>
                        <input class="left" id="search3" type="submit" value=""/>
                        <div class="clr"></div>
                    </div>
                    <input type="hidden" name="lid" value="{{ workLocation_id }}"/>
                    <input type="hidden" name="tid" value="{{ category_id }}"/>
                </div>
                <div id="searchrow2">
                    <div class="srow2l left"></div>
                    <div class="left items pl9 itemnone" id="additems">
                        <a href="/search/?lid=0&tid={{ category_id }}&keywords={{ keywords }}"
                           {% if workLocation_id == 0 %}class="item active" {% else %}
                           class="item" {% endif %}><span><font>全部</font></span></a>
                        {% for workLocation in workLocation_list1 %}
                            {% if workLocation_id == workLocation.id %}
                                <a class="item active"
                                   href="/search/?lid={{ workLocation.id }}&tid={{ category_id }}&keywords={{ keywords }}"><span><font>{{ workLocation }}</font></span></a>
                            {% else %}
                                <a class="item"
                                   href="/search/?lid={{ workLocation.id }}&tid={{ category_id }}&keywords={{ keywords }}"><span><font>{{ workLocation }}</font></span></a>
                            {% endif %}
                        {% endfor %}
                        {% for workLocation in workLocation_list2 %}
                            <a class="item itemhide"
                               href="/search/?lid={{ workLocation.id }}&tid={{ category_id }}&keywords={{ keywords }}"><span><font>{{ workLocation }}</font></span></a>
                        {% endfor %}
                    </div>
                    <div class="left"><a href="javascript:;" class="more2">更多</a></div>
                    <div class="clr"></div>
                </div>
                <div id="searchrow3">
                    <div class="srow2l left"></div>
                    <div class="left items pl9">
                        <a href="/search/?lid={{ workLocation_id }}&tid=0&keywords={{ keywords }}"
                           {% if category_id == 0 %}class="item active" {% else %} class="item" {% endif %}><span><font>全部</font></span></a>
                        {% for category in category_list %}
                            <a {% if category_id == category.id %} class="item active" {% else %}
                                                                   class="item" {% endif %}
                                                                   href="/search/?lid={{ workLocation_id }}&tid={{ category.id }}&keywords={{ keywords }}"><span><font>{{ category }}</font></span></a>
                        {% endfor %}
                    </div>
                    <div class="clr"></div>
                </div>
            </form>
            <table class="tablelist textl" cellpadding="0" cellspacing="0">
                <tr class="h">
                    <td colspan="3" class="l2 bold size16" id="sharetitle">{{ zhaopin.title }}</td>
                </tr>
                <tr class="c bottomline">
                    <td><span class="lightblue l2">工作地点：</span>{{ zhaopin.workLocation }}</td>
                    <td><span class="lightblue">职位类别：</span>{{ zhaopin.category }}</td>
                    <td><span class="lightblue">招聘人数：</span>{{ zhaopin.peopleNumber }}人</td>
                </tr>
                <tr class="c">
                    <td colspan="3" class="l2">
                        <div class="lightblue">招聘要求：</div>
                        <ul class="squareli">
                            {% for job_content in job_content_list %}
                                <li>{{ job_content }}</li>
                            {% endfor %}
                        </ul>
                    </td>
                </tr>
                <tr class="c">
                    <td colspan="3" class="l2">
                        <a href="{% url 'resume:send_resume' zhaopin.id %}" class="but2 left">申请岗位</a>
                        <div id="applyshow" class="ajaxshow none"></div>
                        <div class="clr"></div>
                    </td>
                </tr>
                <tr class="c">
                    <td colspan="3" class="l2">
                        <div class="bshare-custom icon-medium-plus">
                            <div class="bsPromo bsPromo2"></div>
                            <a title="分享到微信" class="bshare-weixin" href="javascript:void(0);"></a>
                            <a title="分享到QQ空间" class="bshare-qzone"></a>
                            <a title="分享到QQ好友" class="bshare-qqim" href="javascript:void(0);"></a>
                            <a title="分享到新浪微博" class="bshare-sinaminiblog" href="javascript:void(0);"></a>
                        </div>
                        <script type="text/javascript" charset="utf-8"
                                src="//static.bshare.cn/b/buttonLite.js#style=-1&amp;uuid=&amp;pophcol=2&amp;lang=zh"></script>
                        <script type="text/javascript" charset="utf-8" src="//static.bshare.cn/b/bshareC0.js"></script>
                    </td>
                </tr>
            </table>
        </div>
    </div>
{% endblock %}
</body>

zhaopin/templates/zhaopin/search.html
{% extends 'base.html' %}
{% block tilte %}
    <title>职位搜索 | 社会招聘 | Tencent 腾讯招聘</title>
{% endblock %}
<body>
{% block content %}
    <div id="sociaheader">
    </div>
    <div id="position" class="maxwidth">
        <a name="a" id="a"></a>
        <div class="left wcont_b box">
            <div class="blueline">
                <div class="butzwss"></div>
            </div>
            <form id="searchform" class="buts1">
                <div id="searchrow1">
                    <div id="search1"><input id="search2" name="keywords" placeholder="请输入关键词" value="{{ keywords }}"
                                             class="left"/>
                        <input class="left" id="search3" type="submit" value=""/>
                        <div class="clr"></div>
                    </div>
                    <input type="hidden" name="lid" value="{{ workLocation_id }}"/>
                    <input type="hidden" name="tid" value="{{ category_id }}"/>
                </div>
                <div id="searchrow2">
                    <div class="srow2l left"></div>
                    <div class="left items pl9 itemnone" id="additems">
                        <a href="?lid=0&tid={{ category_id }}&keywords={{ keywords }}"
                           {% if workLocation_id == 0 %}class="item active" {% else %}
                           class="item" {% endif %}><span><font>全部</font></span></a>
                        {% for workLocation in workLocation_list1 %}
                            {% if workLocation_id == workLocation.id %}
                                <a class="item active"
                                   href="?lid={{ workLocation.id }}&tid={{ category_id }}&keywords={{ keywords }}"><span><font>{{ workLocation }}</font></span></a>
                            {% else %}
                                <a class="item"
                                   href="?lid={{ workLocation.id }}&tid={{ category_id }}&keywords={{ keywords }}"><span><font>{{ workLocation }}</font></span></a>
                            {% endif %}
                        {% endfor %}
                        {% for workLocation in workLocation_list2 %}
                            <a class="item itemhide"
                               href="?lid={{ workLocation.id }}&tid={{ category_id }}&keywords={{ keywords }}"><span><font>{{ workLocation }}</font></span></a>
                        {% endfor %}
                    </div>
                    <div class="left"><a href="javascript:;" class="more2">更多</a></div>
                    <div class="clr"></div>
                </div>
                <div id="searchrow3">
                    <div class="srow2l left"></div>
                    <div class="left items pl9">
                        <a href="?lid={{ workLocation_id }}&tid=0&keywords={{ keywords }}"
                           {% if category_id == 0 %}class="item active" {% else %} class="item" {% endif %}><span><font>全部</font></span></a>
                        {% for category in category_list %}
                            <a {% if category_id == category.id %} class="item active" {% else %}
                                                                   class="item" {% endif %}
                                                                   href="?lid={{ workLocation_id }}&tid={{ category.id }}&keywords={{ keywords }}"><span><font>{{ category }}</font></span></a>
                        {% endfor %}
                    </div>
                    <div class="clr"></div>
                </div>
            </form>
            <table class="tablelist" cellpadding="0" cellspacing="0">
                <tr class="h">
                    <td class="l" width="374">职位名称</td>
                    <td>职位类别</td>
                    <td>人数</td>
                    <td>地点</td>
                    <td>发布时间</td>
                </tr>
                {% for zhaopin in zhaopin_list %}
                    <tr class="even">
                        <td class="l square"><a target="_blank"
                                                href="{% url 'zhaopin:detail' zhaopin.id %}">{{ zhaopin.title }}</a>
                        </td>
                        <td>{{ zhaopin.category }}</td>
                        <td>{{ zhaopin.peopleNumber }}</td>
                        <td>{{ zhaopin.workLocation }}</td>
                        <td>{{ zhaopin.publishTime }}</td>
                    </tr>
                {% endfor %}

                <tr class="f">
                    <td colspan="5">
                        <div class="left">共<span class="lightblue total">{{ list_num }}</span>个职位</div>
                        <div class="right">
                            <div class="pagenav">
                                {% if zhaopin_list.has_previous %}
                                    <a href="?lid={{ workLocation_id }}&tid={{ category_id }}&keywords={{ keywords }}&page={{ zhaopin_list.previous_page_number }}"
                                       id="prev">上一页</a>
                                {% endif %}
                                {% for page_number in page_range %}
                                    {% if zhaopin_list.number == page_number %}
                                        <a class="active"
                                           href="?lid={{ workLocation_id }}&tid={{ category_id }}&keywords={{ keywords }}&page={{ page_number }}">{{ page_number }}</a>
                                    {% else %}
                                        <a href="?lid={{ workLocation_id }}&tid={{ category_id }}&keywords={{ keywords }}&page={{ page_number }}">{{ page_number }}</a>
                                    {% endif %}
                                {% endfor %}

                                {% if zhaopin_list.has_next %}
                                    <a href="?lid={{ workLocation_id }}&tid={{ category_id }}&keywords={{ keywords }}&page={{ zhaopin_list.next_page_number }}"
                                       id="next">下一页</a>
                                {% endif %}

                                <div class="clr"></div>
                            </div>
                        </div>
                        <div class="clr"></div>
                    </td>
                </tr>
            </table>
        </div>
        <div class="right wcont_s box">
            <div class="blueline">
                <div class="butcjwt"></div>
            </div>
            <div class="module_faqs square"><a href="faq.php?id=5" title="如何应聘腾讯公司的职位？">如何应聘腾讯公司的职位？</a><a
                    href="faq.php?id=3" title="应届生如何应聘？">应届生如何应聘？</a><a href="faq.php?id=19"
                                                                        title="腾讯应聘流程是什么？">腾讯应聘流程是什么？</a><a
                    href="faq.php?id=20" title="我注册了简历，但为什么没有人联系我？">我注册了简历，但为什么没...</a><a href="faq.php?id=22"
                                                                                          title="我忘记密码了，怎么办？">我忘记密码了，怎么办？</a><a
                    href="faq.php?id=23" title="如何进行简历修改？">如何进行简历修改？</a></div>
        </div>
        <div class="clr"></div>
    </div>
{% endblock %}
</body>
</html>

zhaopin/templates/zhaopin/social.html
{% extends 'base.html' %}
{% block tilte %}
    <title>社会招聘 | Tencent 腾讯招聘</title>
{% endblock %}
<body>
{% block content %}
    <div id="sociaheader">
    </div>
    <div class="content" id="socia_cont">
        <div class="maxwidth">
            <div id="socia_l">
                <form action="/search/?lid={{ workLocation.id }}&tid={{ category.id }}&keywords={{ keywords }}">
                    <div id="socia_search">
                        <div class="select">
                            <input class="val" name="lid" type="hidden" value="{{ worklocation.id }}"/>
                            <div class="show">-全部工作点-</div>
                            <div class="options">
                                <div class="option" val="">-全部工作点-</div>
                                {% for worklocation in workLocation_list %}
                                    <div class="option" val="{{ worklocation.id }}">{{ worklocation }}</div>
                                {% endfor %}
                            </div>
                        </div>
                        <div class="select ml9">
                            <input class="val" name="tid" type="hidden" value="{{ category.id }}"/>
                            <div class="show">-全部职位类别-</div>
                            <div class="options">
                                <div class="option" val="">-全部职位类别-</div>
                                {% for category in category_list %}
                                    <div class="option" val="{{ category.id }}">{{ category }}</div>
                                {% endfor %}
                            </div>
                        </div>

                        <div class="right" style="padding-top:1px;background-position:0 1px;" id="search1">
                            <input name="keywords" id="hsearch" class="left" placeholder="请输入关键词"/>
                            <input type="submit" id="hshearbut" value="" class="left pointer"/>
                            <div class="clr"></div>
                        </div>
                        <div class="clear"></div>
                    </div>
                </form>
                <div id="socia_hot">
                    <div class="more"><a href="/search/?lid=0&tid=0&keywords={{ keywords }}">更多&gt;&gt;</a></div>
                    <table>
                        <!-- 一个tr输入两个数据 -->
                        <tr>
                            <td>
                                {% for zhaopin1 in zhaopin_list1 %}
                                    <a href="{% url 'zhaopin:detail' zhaopin1.id %}"
                                       title="{{ zhaopin1 }}">{{ zhaopin1 | truncatechars:17 }}</a><br>
                                {% endfor %}
                            </td>
                            <td width="87" class="date">

                            </td>
                            <td>
                                {% for zhaopin2 in zhaopin_list2 %}
                                    <a href="{% url 'zhaopin:detail' zhaopin2.id %}"
                                       title="{{ zhaopin2 }}">{{ zhaopin2 | truncatechars:17 }}</a><br>
                                {% endfor %}
                            </td>
                            <td width="84" align="right" class="date">

                            </td>
                        </tr>
                    </table>
                </div>
                <!--<div id="socia_senior">-->
                <!--<p>如果你是某个领域的精英，欢迎加入我们，一起改变7亿网民的在线生活！</p>-->
                <!--<a href="senior.php" class="more3">我要应聘高级职位</a>-->
                <!--</div>-->
            </div>
            <div id="socia_r">
                <div id="socia_news">
                    <div class="more"><a href="news.php">更多&gt;&gt;</a></div>
                    <div class="c square">
                        <a target="_blank" href="https://hr.tencent.com/news_detail.php?id=268" title="MIG2018年春季专场招聘会">MIG2018年春季专场招聘会</a>
                        <a target="_blank" href="https://hr.tencent.com/news_detail.php?id=267" title="腾讯SNG春季技术专场招聘会">腾讯SNG春季技术专场招聘会</a>
                        <a target="_blank" href="https://hr.tencent.com/news_detail.php?id=266" title="腾讯热招AI职位集锦">腾讯热招AI职位集锦</a>
                        <a target="_blank" href="https://hr.tencent.com/news_detail.php?id=265" title="诚邀众俠，仗剑江湖 ">诚邀众俠，仗剑江湖 </a>
                        <a target="_blank" href="https://hr.tencent.com/news_detail.php?id=264" title="《王者荣耀》全球版期待你的加入">《王者荣耀》全球版期待你的加入</a>
                        <a target="_blank" href="https://hr.tencent.com/news_detail.php?id=263" title="欢乐游戏，“职”得拥有">欢乐游戏，“职”得拥有</a>
                    </div>
                </div>
                <div id="socia_faq">
                    <div class="more"><a target="_blank" href="https://hr.tencent.com/faq.php">更多&gt;&gt;</a></div>
                    <div class="c square">
                        <a target="_blank" href="https://hr.tencent.com/faq.php?id=5">如何应聘腾讯公司的职位？</a>
                        <a target="_blank" href="https://hr.tencent.com/faq.php?id=3">应届生如何应聘？</a>
                        <a target="_blank" href="https://hr.tencent.com/faq.php?id=19">腾讯应聘流程是什么？</a>
                        <a target="_blank" href="https://hr.tencent.com/faq.php?id=20">我注册了简历，但为什么没有人联系我？</a>
                        <a target="_blank" href="https://hr.tencent.com/faq.php?id=22">我忘记密码了，怎么办？</a>
                    </div>
                </div>
            </div>
            <div class="clr"></div>
        </div>
    </div>
{% endblock %}
</body>