about/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^info/$', info, name='info'),
    url(r'^branch/$', branch, name='branch'),
    url(r'^business/$', business, name='business'),
    url(r'^culture/$', culture, name='culture'),
]

tencentHR/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('zhaopin.urls', namespace='zhaopin')),
    url(r'^about/', include('about.urls', namespace='about')),
    url(r'^inTencent/', include('inTencent.urls', namespace='inTencent')),
    # url(r'^search/',include('haystack.urls')),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^users/',include('django.contrib.auth.urls')),
    url(r'^resume/',include('resume.urls',namespace='resume'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.conf.urls import url
from .views import (register_can, register_rec, login_can, login_rec, logout,
                    edit_info_cand, edit_resume_cand, edit_info_rec, resume_list,
                    send_zhaopin_list, zhaopin_detail)
from .chart import histogram, line

urlpatterns = [
    url(r'^register_can/$', register_can, name='register_can'),
    url(r'^register_rec/$', register_rec, name='register_rec'),
    url(r'^login_can/$', login_can, name='login_can'),
    url(r'^login_rec/$', login_rec, name='login_rec'),
    url(r'^logout/$', logout, name='logout'),
    url(r'^edit_info_cand/(?P<id>\d+)/$', edit_info_cand, name='edit_info_cand'),
    url(r'^edit_resume_cand/(?P<id>\d+)/$', edit_resume_cand, name='edit_resume_cand'),
    url(r'^edit_info_rec/(?P<id>\d+)/$', edit_info_rec, name='edit_info_rec'),
    url(r'^resume_list/$', resume_list, name='resume_list'),
    url(r'^zhaopin_list/$', send_zhaopin_list, name='send_zhaopin_list'),
    url(r'^zhaopin_detail/(?P<id>\d+)/$', zhaopin_detail, name='zhaopin_detail'),

    url(r'^histogram/$', histogram, name='histogram'),
    url(r'^line/$', line, name='line'),
]

users/models.py
from django.db import models
from django.contrib.auth.hashers import make_password, check_password


# Create your models here.
class Candidaters(models.Model):
    username = models.CharField(max_length=20, verbose_name='用户名')
    password1 = models.CharField(max_length=128, verbose_name='密码')
    password2 = models.CharField(max_length=128, verbose_name='密码确认')
    tel = models.CharField(max_length=20, verbose_name='手机')
    email = models.EmailField(verbose_name='邮箱')
    headshot = models.ImageField(upload_to='avatar/%Y/%m/%d', default='default.jpg',
                                 verbose_name='头像', null=True, blank=True)

    def __str__(self):
        return self.username

    def save(self, *args, **kwargs):
        self.password1 = self.password2 = set_password(self.password1)
        super(Candidaters, self).save(*args, **kwargs)


class Recruiter(models.Model):
    username = models.CharField(max_length=20, verbose_name='用户名')
    password1 = models.CharField(max_length=128, verbose_name='密码')
    password2 = models.CharField(max_length=128, verbose_name='密码确认')
    tel = models.CharField(max_length=20, verbose_name='手机')
    email = models.EmailField(verbose_name='邮箱')
    department = models.CharField(max_length=30, verbose_name='部门', null=True, blank=True)

    def __str__(self):
        return self.username

    def save(self, *args, **kwargs):
        self.password1 = self.password2 = set_password(self.password1)
        super(Recruiter, self).save(*args, **kwargs)


def set_password(password):
    # 设置密码
    password_hash = make_password(password)
    return password_hash


def check_password_hash(password, password_hash):
    return check_password(password, password_hash)

users/forms.py
from .models import Candidaters, Recruiter
from django import forms
from resume.models import Resume


class CanRegisterForm(forms.ModelForm):
    class Meta:
        model = Candidaters
        fields = '__all__'

        css = {'class': "longinput3 changeCheck", 'size': "35", 'maxlength': "60"}
        widgets = {
            'username': forms.TextInput(attrs=css),
            'password1': forms.PasswordInput(attrs=css),
            'password2': forms.PasswordInput(attrs=css),
            'headshot': forms.FileInput(attrs=css),
            'email': forms.EmailInput(attrs=css),
            'tel': forms.TextInput(attrs=css),
        }


class RecRegisterForm(forms.ModelForm):
    class Meta:
        model = Recruiter
        fields = '__all__'

        css = {'class': "longinput3 changeCheck", 'size': "35", 'maxlength': "60"}
        widgets = {
            'username': forms.TextInput(attrs=css),
            'password1': forms.PasswordInput(attrs=css),
            'password2': forms.PasswordInput(attrs=css),
            'department': forms.TextInput(attrs=css),
            'email': forms.EmailInput(attrs=css),
            'tel': forms.TextInput(attrs=css),
        }


class ResumeForm(forms.ModelForm):
    class Meta:
        model = Resume
        fields = ['name', 'age', 'sex', 'address', 'school', 'experience', 'evaluation']

users/views.py
from django.shortcuts import render, HttpResponse, redirect, reverse
from django.http import HttpResponseRedirect

from users import models
from .forms import RecRegisterForm, CanRegisterForm
from django.contrib import messages
from .models import Recruiter, Candidaters
from .models import set_password, check_password_hash
from resume.forms import ResumeForm
from resume.models import Resume, Resume_relationship
from zhaopin.models import Zhaopin


# Create your views here.


def register_can(request):
    if request.method == 'POST':
        form = CanRegisterForm(request.POST, request.FILES)
        # 数据提交是否合法
        if form.is_valid():
            username = form.cleaned_data['username']
            # 用户名已存在,返回注册页面
            if len(Candidaters.objects.filter(username=username)) != 0:
                # messages.info(request, '用户名已存在!')
                info = {'error': '用户名已存在!'}
                return render(request, 'users/register.html', info)
            else:
                password1 = form.cleaned_data['password1']
                password2 = form.cleaned_data['password2']
                if password1 != password2:
                    # messages.info(request, '两次密码输入不一致!')
                    info = {'error': '两次密码输入不一致!'}
                    return render(request, 'users/register.html', info)
                else:
                    # 加密放在了model里进行操作
                    form.save()
                    messages.success(request, '注册成功!')
                    return HttpResponseRedirect('/index')
    else:
        form = CanRegisterForm()
    return render(request, 'users/register.html', locals())


def register_rec(request):
    if request.method == 'POST':
        form = RecRegisterForm(request.POST, request.FILES)
        # 数据提交是否合法
        if form.is_valid():
            username = form.cleaned_data['username']
            # 用户名已存在,返回注册页面
            if len(Recruiter.objects.filter(username=username)) != 0:
                messages.error(request, '用户名已存在!')
                return render(request, 'users/register.html', locals())
            else:
                password1 = form.cleaned_data['password1']
                password2 = form.cleaned_data['password2']
                if password1 != password2:
                    messages.error(request, '两次密码输入不一致!')
                    return render(request, 'users/register.html', locals())
                else:
                    # 加密放在了model里进行操作
                    form.save()
                    messages.success(request, '注册成功!')
                    return HttpResponseRedirect('/index')
    else:
        form = RecRegisterForm()
    return render(request, 'users/register.html', locals())


def login_can(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        # 检查用户是否存在
        cand = Candidaters.objects.filter(username=username).first()
        # 用户不存在
        if cand == None:
            messages.error(request, '用户名或密码错误!')
            return render(request, 'users/login_cand.html', locals())
        password1 = cand.password1
        # 校验密码是否正确
        # 密码错误
        if not check_password_hash(password, password1):
            messages.error(request, '用户名或密码错误!')
            return render(request, 'users/login_cand.html', locals())

        request.session['username'] = cand.username
        request.session['id'] = cand.id
        request.session['mark'] = 0
        messages.success(request, '登录成功!')
        return HttpResponseRedirect('/index')
    return render(request, 'users/login_cand.html', locals())


def login_rec(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        department = request.POST.get('department')

        # 检查用户是否存在
        rec = Recruiter.objects.filter(username=username).first()
        # 用户不存在
        if rec == None:
            messages.error(request, '用户名或密码错误!')
            return render(request, 'users/login_rec.html', locals())
        password1 = rec.password1
        # 校验密码是否正确
        # 密码错误
        if not check_password_hash(password, password1):
            messages.error(request, '用户名或密码错误!')
            return render(request, 'users/login_rec.html', locals())
        # 部门名不正确
        if department != rec.department:
            messages.error(request, '用户名或密码错误!')
            return render(request, 'users/login_rec.html', locals())
        request.session['username'] = rec.username
        request.session['id'] = rec.id
        request.session['mark'] = 1
        messages.success(request, '登录成功!')
        return HttpResponseRedirect('/index')
    return render(request, 'users/login_rec.html', locals())


def logout(request):
    request.session.flush()
    return redirect(reverse('zhaopin:index'))


def edit_info_cand(request, id):
    cand = Candidaters.objects.get(id=id)
    if request.method == 'POST':
        username = request.POST.get('username')
        email = request.POST.get('email')
        tel = request.POST.get('tel')
        headshot = request.FILES.get('headshot') or 'default.jpg'
        models.Candidaters.objects.filter(id=id).update(username=username,
                                                        email=email, headshot=headshot, tel=tel)
        # info = {'message': '修改成功!'}
        messages.success(request, '修改成功!')
        return HttpResponseRedirect('/users/edit_info_cand/%s' % id, )
    return render(request, 'candidaters/can_info_edit.html', locals())


def edit_resume_cand(request, id):
    resume = Resume.objects.filter(user_id=id).first()
    if request.method == 'POST':
        form = ResumeForm(request.POST, instance=resume)
        if form.is_valid():
            try:
                # 修改简历
                form.save()
                messages.success(request, '简历修改成功!')
            except:
                # 创建简历
                form.cleaned_data['user_id'] = int(id)
                Resume.objects.create(**form.cleaned_data)
                messages.success(request, '简历创建成功!')
    else:
        form = ResumeForm(instance=resume)
    return render(request, 'candidaters/can_resume_edit.html', locals())


def edit_info_rec(request, id):
    rec = Recruiter.objects.get(id=id)
    if request.method == 'POST':
        username = request.POST.get('username')
        email = request.POST.get('email')
        tel = request.POST.get('tel')
        department = request.POST.get('department')
        models.Recruiter.objects.filter(id=id).update(username=username,
                                                      email=email, department=department, tel=tel)
        messages.success(request, '修改成功!')
        return HttpResponseRedirect('/users/edit_info_rec/%s' % id, )
    return render(request, 'recruiter/rec_info_edit.html', locals())


def resume_list(request):
    try:
        rec_id = int(request.session['id'])
        resume_id_list = Resume_relationship.objects.filter(rec_id=rec_id)
        resume_list = [Resume.objects.filter(id=resume_id.resume_id)[0] for resume_id in resume_id_list]
        # 去重
        resume_list = set(resume_list)
    except:
        info = '暂无投递简历!'
    return render(request, 'recruiter/rec_resume_list.html', locals())


# 已投递的招聘岗位
def send_zhaopin_list(request):
    try:
        # 候选人id
        cand_id = int(request.session['id'])
        # 候选人对应简历
        resume = Resume.objects.filter(user_id=cand_id).first()
        # 候选人投递的岗位
        zhaopin_id_list = Resume_relationship.objects.filter(resume_id=resume.id)
        zhaopin_list = [Zhaopin.objects.filter(id=zhaopin_id.zhaopin_id)[0] for zhaopin_id in zhaopin_id_list]
    except:
        info = '还未投递简历,赶紧去看看吧'
    return render(request, 'candidaters/send_zhaopin_list.html', locals())


def zhaopin_detail(request, id):
    return HttpResponseRedirect('/detail/%s/' % id)

users/templates/users/changeinfo.html
{% extends 'base.html' %}
{% block tilte %}

    <title>修改信息 | 社会招聘 | Tencent 腾讯招聘</title>
    <style>
        .errorlist {
            color: red;
        }
    </style>
{% endblock %}
<body>
{% block content %}
    </div>
    <div id="reg0" class="maxwidth">
        <div class="box wcont_a">
            <div class="blueline">
            </div>

                    <form action="{% url 'users:change_info' user.id %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <table class="reg" cellpadding="0" cellspacing="0">
                            邮箱:{{ form.email }}<br>
                            手机:{{ form.tel }}<br>
                            头像:{{ form.headshot }}<br>
                            <img src="{{ user.headshot.url }}" width="100px" height="100px"><br>
                             <tr>
                                <td></td>
                                <td>
                                    <div class="height20"></div>
                                    <input type="submit" class="but4" id="btnSubmit" value="确　定">
                                </td>
                            </tr>
                        </table>
                    </form>
                </div>
                <br>
            </div>
{% endblock %}
</body>

users/templates/users/login_cand.html
{% extends 'base.html' %}
{% block tilte %}
    <title>用户登录 | 社会招聘 | Tencent 腾讯招聘</title>
{% endblock %}


{% block content %}
    <div id="login" class="maxwidth">
        <div class="box wcont_a">
            <div class="blueline">
                <div class="butlogin"></div>
            </div>
            <div id="logindiv">
                <form onsubmit="return checkCommonLogin();" id="frm_user_login_common" name="frm_user_login_common"
                      method="post" action="">
                    {% csrf_token %}
                    <table cellpadding="0" cellspacing="0">
                        {% if info.error %}
                            <tr class="bottom0">
                                <td></td>
                                <td style="font-family: 微软雅黑"><b>{{ info.error }}</b></td>
                                <td></td>
                            </tr>
                        {% endif %}
                        <tr class="bottom0">
                            <td align="right" width="80" class="k">用户名：</td>
                            <td>
                                <input class="longinput3 changeCheck" style="size:35px;width:175px" id="username_common"
                                       name="username" type="text" value=""
                                       onblur="return checkLoginEmailCommon()" tabindex="11"/>
                            </td>
                            <td>
                                <a {% if 'can' in request.path %} href="{% url 'users:register_can' %}"
                                {% else %} href="{% url 'users:register_rec' %}" {% endif %} >注册新用户</a>
                            </td>
                        </tr>
                        <tr class="errortd">
                            <td></td>
                            <td>
                                <div class="height20"><span id="msg_LoginEmail_common" class="clew"></span></div>
                            </td>
                        </tr>
                        <tr class="bottom0">
                            <td align="right" class="k" style="padding-top:12px;" valign="top">登录密码：</td>
                            <td>
                                <input class="longinput3 changeCheck" style="size:35px;width:175px"
                                       id="password_common" name="password" type="password" value=""
                                       onblur="return checkPasswordCommon()" tabindex="12"/>
                            </td>
                            <td><a href="#">忘了密码？</a></td>
                        </tr>
                        <tr class="errortd">
                            <td></td>
                            <td>
                                <div class="height20"><span id="msg_Password_common" class="clew"></span></div>
                            </td>
                        </tr>

                        <tr>
                            <td></td>
                            <td style="width: 190px">
                                <button type="submit" class="but2"
                                        style="word-wrap:break-word;word-break:break-all;">登　录
                                </button>
                            </td>
                            <td>
                                <a href="{% url 'users:login_rec' %}">企业版登录</a>
                            </td>
                        </tr>
                    </table>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/login_rec.html
{% extends 'base.html' %}
{% block tilte %}
    <title>用户登录 | 社会招聘 | Tencent 腾讯招聘</title>
{% endblock %}


{% block content %}
    <div id="login" class="maxwidth">
        <div class="box wcont_a">
            <div class="blueline">
                <div class="butlogin"></div>
            </div>
            <div id="logindiv">
                <form onsubmit="return checkCommonLogin();" id="frm_user_login_common" name="frm_user_login_common"
                      method="post" action="">
                    {% csrf_token %}
                    <table cellpadding="0" cellspacing="0">
                        {% if info.error %}
                            <tr class="bottom0">
                                <td></td>
                                <td style="font-family: 微软雅黑"><b>{{ info.error }}</b></td>
                                <td></td>
                            </tr>
                        {% endif %}
                        <tr class="bottom0">
                            <td align="right" width="80" class="k">用户名：</td>
                            <td>
                                <input class="longinput3 changeCheck" style="size:35px;width:175px" id="username_common"
                                       name="username" type="text" value=""
                                       onblur="return checkLoginEmailCommon()" tabindex="11"/>
                            </td>
                            <td>
                                <a {% if 'can' in request.path %} href="{% url 'users:register_can' %}"
                                {% else %} href="{% url 'users:register_rec' %}" {% endif %} >注册新用户</a>
                            </td>
                        </tr>
                        <tr class="errortd">
                            <td></td>
                            <td>
                                <div class="height20"><span id="msg_LoginEmail_common" class="clew"></span></div>
                            </td>
                        </tr>

                        <tr class="bottom0">
                            <td align="right" class="k" style="padding-top:12px;" valign="top">登录密码：</td>
                            <td>
                                <input class="longinput3 changeCheck" style="size:35px;width:175px"
                                       id="password_common" name="password" type="password" value=""
                                       onblur="return checkPasswordCommon()" tabindex="12"/>
                            </td>
                            <td>
                                <a href="#">忘了密码？</a>
                            </td>
                        </tr>
                        <tr class="errortd">
                            <td></td>
                            <td>
                                <div class="height20"><span id="msg_LoginEmail_common" class="clew"></span></div>
                            </td>
                        </tr>

                        <tr class="bottom0">
                            <td align="right" class="k" style="padding-top:12px;" valign="top">部门：</td>
                            <td>
                                <input class="longinput3 changeCheck" style="size:35px;width:175px"
                                       id="department_common" name="department" type="text" value=""
                                       onblur="return checkPasswordCommon()" tabindex="12"/>
                            </td>
                        </tr>

                        <tr class="errortd">
                            <td></td>
                            <td>
                                <div class="height20"><span id="msg_Password_common" class="clew"></span></div>
                            </td>
                        </tr>

                        <tr>
                            <td></td>
                            <td style="width: 190px">
                                <button type="submit" class="but2"
                                        style="word-wrap:break-word;word-break:break-all;">登　录
                                </button>
                            </td>
                            <td>
                                <a href="{% url 'users:login_can' %}">个人版登录</a>
                            </td>
                        </tr>
                    </table>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/register.html
{% extends 'base.html' %}
{% block tilte %}

    <title>注册账户 | 社会招聘 | Tencent 腾讯招聘</title>
    <style>
        .errorlist {
            color: red;
        }
    </style>
{% endblock %}
<body>
{% block content %}
    </div>
    <div id="reg0" class="maxwidth">
        <div class="box wcont_a">
            <div class="blueline">
                <div class="butreg0"></div>
            </div>

            <div id="frm_reg1" name="frm_reg1">
                <input id="type" type="hidden" name="type" value="0"/>
                <div id="reg_content" class="regtitlebg">
                    <div class="regtitle">基本信息</div>
                    <form {% if 'register_can' in request.path %} action="{% url 'users:register_can' %}" {% else %}
                                                                  action="{% url 'users:register_rec' %}"  {% endif %}method="post"
                                                                  enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ error }}
                        <table class="reg" cellpadding="0" cellspacing="0">
                            {% for field in form %}
                                <tr>
                                    <td class="k row2in1" valign="top">
                                        {{ field.label_tag }}
                                    </td>
                                    <td>
                                        {{ field }}<br>
                                    </td>
                                    <td>
                                        {{ field.errors }}
                                    </td>
                                    <td>
                                        {% if field.help_text %}
                                            <p class="help text-small text-muted">{{ field.help_text|safe }}</p>
                                        {% endif %}
                                    </td>
                                </tr>
                            {% endfor %}
                            <tr>
                                <td></td>
                                <td>
                                    <div class="height20"></div>
                                    <input type="submit" class="but4" id="btnSubmit" value="确　定">
                                </td>
                            </tr>
                        </table>
                    </form>
                </div>
                <br>
                <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    {% if 'register_rec' in request.path %}
                        <td><a href="{% url 'users:register_can' %}">个人版注册</a></td>
                    {% else %}
                        <td><a href="{% url 'users:register_rec' %}">企业版注册</a></td>
                    {% endif %}
                </tr>
            </div>
        </div>
    </div>

{% endblock %}
</body>