about/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^info/$', info, name='info'),
    url(r'^branch/$', branch, name='branch'),
    url(r'^business/$', business, name='business'),
    url(r'^culture/$', culture, name='culture'),
]

inTencent/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^work/$', work, name='work'),
    url(r'^live/$', live, name='live'),
    url(r'^training/$', training, name='training'),
    url(r'^welfare/$', welfare, name='welfare'),

]

tencentHR/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('zhaopin.urls', namespace='zhaopin')),
    url(r'^about/', include('about.urls', namespace='about')),
    url(r'^inTencent/', include('inTencent.urls', namespace='inTencent')),
    # url(r'^search/',include('haystack.urls')),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^users/',include('django.contrib.auth.urls')),
    url(r'^resume/',include('resume.urls',namespace='resume'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.conf.urls import url
from .views import (register_can, register_rec, login_can, login_rec, logout,
                    edit_info_cand, edit_resume_cand, edit_info_rec, resume_list,
                    send_zhaopin_list, zhaopin_detail)
from .chart import histogram, line

urlpatterns = [
    url(r'^register_can/$', register_can, name='register_can'),
    url(r'^register_rec/$', register_rec, name='register_rec'),
    url(r'^login_can/$', login_can, name='login_can'),
    url(r'^login_rec/$', login_rec, name='login_rec'),
    url(r'^logout/$', logout, name='logout'),
    url(r'^edit_info_cand/(?P<id>\d+)/$', edit_info_cand, name='edit_info_cand'),
    url(r'^edit_resume_cand/(?P<id>\d+)/$', edit_resume_cand, name='edit_resume_cand'),
    url(r'^edit_info_rec/(?P<id>\d+)/$', edit_info_rec, name='edit_info_rec'),
    url(r'^resume_list/$', resume_list, name='resume_list'),
    url(r'^zhaopin_list/$', send_zhaopin_list, name='send_zhaopin_list'),
    url(r'^zhaopin_detail/(?P<id>\d+)/$', zhaopin_detail, name='zhaopin_detail'),

    url(r'^histogram/$', histogram, name='histogram'),
    url(r'^line/$', line, name='line'),
]

zhaopin/urls.py
from django.conf.urls import url
from .views import (index, detail, social, SearchView, add_zhaopin,)

urlpatterns = [
    url(r'^index/$', index, name='index'),
    url(r'^detail/(?P<pk>\d+)/$', detail, name='detail'),
    url(r'^social/$', social, name='social'),
    url(r'^search/$', SearchView.as_view(), name='search'),
    url(r'^add_zhaopin', add_zhaopin, name='add_zhaopin'),

]

templates/base.html
{% block head %}
    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
            "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
    <html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        {% block tilte %}
            <title>首页 | Tencent 腾讯招聘</title>
        {% endblock %}
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

        <!-- Js Css -->
        <link media="screen" href="//cdn.m.tencent.com/hr_static/css/all.css?max_age=86412" type="text/css"
              rel="stylesheet"/>
        <script type="text/javascript" src="//cdn.m.tencent.com/hr_static/js/jquery-1.7.2.min.js"></script>
        <script type="text/javascript" src="//cdn.m.tencent.com/hr_static/js/jquery-ui-1.7.2.custom.min.js"></script>
        <script type="text/javascript" src="//cdn.m.tencent.com/hr_static/js/thickbox.js"></script>
        <link media="screen" href="//cdn.m.tencent.com/hr_static/css/thickbox.css" type="text/css" rel="stylesheet"/>
        <script type="text/javascript" src="//cdn.m.tencent.com/hr_static/js/functions.js"></script>
        <script type="text/javascript" src="//cdn.m.tencent.com/hr_static/js/utils.js"></script>
        <script language="javascript" src="//vm.gtimg.cn/tencentvideo/txp/js/txplayer.js" charset="utf-8"></script>
        <script type="text/javascript" src="//cdn.m.tencent.com/hr_static/js/all.js?max_age=86412"></script>

        <style>
            span.highlighted {
                color: red;
            }
        </style>

    </head>
{% endblock %}
<body>
<div id="header">
    <div class="maxwidth">
        <a href="{% url 'zhaopin:index' %}" class="left" id="logo"><img
                src="//cdn.m.tencent.com/hr_static/img/logo.png"/></a>
        <div class="right" id="headertr">
            <div class="right pl9" id="topshares">
                <div class="shares">
                    <span class="left">分享到：</span>
                    <!--<a href="javascript:;" onclick="shareto('qqt','top');" id="qqt" title="分享到腾讯微博">分享到腾讯微博</a>-->
                    <a href="javascript:;" onclick="shareto('qzone','top');" id="qzone" title="分享到QQ空间">分享到QQ空间</a>
                    <!--<a href="javascript:;" onclick="shareto('pengyou','top');" id="pengyou" title="分享到腾讯朋友">分享到腾讯朋友</a>-->
                    <a href="javascript:;" onclick="shareto('sinat','top');" id="sinat" title="分享到新浪微博">分享到新浪微博</a>
                    <!--<a href="javascript:;"  onclick="shareto('renren','top');"id="renren" title="分享到人人网">分享到人人网</a>-->
                    <!--<a href="javascript:;"  onclick="shareto('kaixin001','top');"id="kaixin" title="分享到开心网">分享到开心网</a>-->
                    <div class="clr"></div>
                </div>
                <!--<a href="javascript:;">分享</a>-->
            </div>
            <!--<div class="right pl9">-->
            <!--<a href="http://t.qq.com/QQjobs" id="tqq" target="_blank">收听腾讯招聘</a>-->
            <!--</div>-->
            <div class="right pr9">
                {% block nav %}
                    {% if request.session.username %}
                        <seclect></seclect>
                        {% if request.session.mark == 0 %}
                            <a href="{% url 'users:edit_info_cand' request.session.id %}"
                               id="header_login_anchor">{{ request.session.username }}</a>
                        {% endif %}
                        {% if request.session.mark == 1 %}
                            <a href="{% url 'users:edit_info_rec' request.session.id %}"
                               id="header_login_anchor">{{ request.session.username }}</a>
                        {% endif %}
                        <span class="plr9">|</span><a href="{% url 'users:logout' %}">注销</a>
                    {% else %}
                        <a href="{% url 'users:login_can' %}" id="header_login_anchor">登录</a><span class="plr9">|</span>
                        <a href="{% url 'users:register_can' %}">注册</a>
                    {% endif %}
                    <span class="plr9">|</span><a href="#">反馈建议</a>
                    <span class="plr9">|</span>
                    <a href="http://careers.tencent.com/global" target="_blank">Tencent Global
                        Talent</a>
                {% endblock %}
                <script>
                    var User_Account = "";
                </script>
            </div>
            <div class="clr"></div>
        </div>
        <div class="clr"></div>
    </div>
    <div id="menus">
        <div class="maxwidth">
            <ul id="menu" class="left">
                <li id="nav1" {% if request.path == '/index/' %} class="active" {% endif %}><a
                        href="{% url 'zhaopin:index' %}">&nbsp;</a></li>
                <li id="nav2" {% if request.path == '/social/' %}class="active" {% endif %}><a
                        href="{% url 'zhaopin:social' %}">&nbsp;</a></li>
                <li id="nav3" {% if  'about' in request.path %}class="active" {% endif %}><a
                        href="{% url 'about:info' %}">&nbsp;</a></li>
                <li id="nav4" {% if  'inTencent' in request.path %}class="active" {% endif %}><a
                        href="{% url 'inTencent:work' %}">&nbsp;</a></li>
            </ul>
            <a class="right texti9" target="_blank" id="navxy" href="http://join.qq.com">校园招聘</a>
            <div class="clr"></div>
        </div>
    </div>
    <h4>
        {% for message in messages %}
            <div class="alert alert-warning alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span>
                </button>
                <strong>{{ message }}</strong>
            </div>
        {% endfor %}
    </h4>
</div>
{% block banner %}
{% endblock %}
{% block content %}
{% endblock %}


<div id="homeDep">
    <table id="homeads">
        <tr>
            <td align="center"><a href="http://tencent.avature.net/career" target="blank">全球招聘</a></td>
            <td align="center"><a href="http://game.qq.com/hr/" target="blank">互动娱乐事业群招聘</a></td>
            <td align="center"><a href="http://hr.tencent.com/position.php?lid=&tid=&keywords=WXG" target="blank">微信事业群招聘</a>
            </td>
            <td align="center"><a href="http://hr.qq.com/" target="blank">技术工程事业群招聘</a></td>
            <td align="center"><a href="http://snghr.tencent.com" target="blank">社交网络事业群招聘</a></td>
            <td align="center"><a href="http://mighr.qq.com" target="blank">移动互联网事业群招聘</a></td>
            <td align="center"><a href="http://hr.tencent.com/position.php?keywords=OMG" target="blank">网络媒体事业群招聘</a>
            </td>
        </tr>
    </table>
</div>
<div id="footer">
    <div>
        <a href="http://www.tencent.com/" target="_blank">关于腾讯</a><span>|</span><a
            href="http://www.qq.com/contract.shtml" target="_blank">服务条款</a><span>|</span><a
            href="http://hr.tencent.com/" target="_blank">腾讯招聘</a><span>|</span><a
            href="http://careers.tencent.com/global" target="_blank">Tencent Global Talent</a><span>|</span><a
            href="http://gongyi.qq.com/" target="_blank">腾讯公益</a><span>|</span><a href="http://service.qq.com/"
                                                                                  target="_blank">客服中心</a>
    </div>
    <p>Copyright &copy; 1998 - 2018 Tencent. All Rights Reserved.</p>
</div>
<script type="text/javascript" src="//tajs.qq.com/stats?sId=64934792" charset="UTF-8"></script>
</body>
{% block js %}
{% endblock %}
</html>

templates/index.html
{% extends 'base.html' %}
{% block  banner %}
    <div id="home_banner">
        <a onClick="pgvSendClick({hottag:'HRTENCENT.HOME.BANNER.BANNER222'});"
           href="https://hr.tencent.com/news_detail.php?id=265" id="big_a">
            <div id="big_img"
                 style="background-image:url(http://3gimg.qq.com/daxue_qq_com/image/201802/1519813663896.jpg)"></div>
        </a>
        <div class="relative">
            <div id="small_img">
                <div class="maxwidth">
                    <a id="small_pre"></a>
                    <div id="small_imgs">
                        <a href="javascript:;" class="item">
                            <div title="诚邀众俠，仗剑江湖" class="img active"
                                 b="http://3gimg.qq.com/daxue_qq_com/image/201802/1519813663896.jpg"
                                 l="https://hr.tencent.com/news_detail.php?id=265" theid="222"><img
                                    src="http://3gimg.qq.com/daxue_qq_com/image/201802/1519813658370.jpg"/></div>
                        </a>
                        <a href="javascript:;" class="item">
                            <div title="https://hr.tencent.com/news_detail.php?id=267" class="img"
                                 b="https://3gimg.qq.com/daxue_qq_com/image/201803/1520504916519.jpg"
                                 l="https://hr.tencent.com/news_detail.php?id=267" theid="223"><img
                                    src="https://3gimg.qq.com/daxue_qq_com/image/201803/1520504911790.jpg"/></div>
                        </a>
                        <a href="javascript:;" class="item">
                            <div title="MIG2018年春季专场招聘会" class="img"
                                 b="http://3gimg.qq.com/daxue_qq_com/image/201803/1521094452448.jpg"
                                 l="https://hr.tencent.com/news_detail.php?id=268" theid="224"><img
                                    src="http://3gimg.qq.com/daxue_qq_com/image/201803/1521094457656.png"/></div>
                        </a>
                        <a href="javascript:;" class="item">
                            <div title="做个伟大的产品，取悦自己！" class="img"
                                 b="http://3gimg.qq.com/daxue_qq_com/image/201707/1500018068445.png"
                                 l="http://hr.tencent.com/news_detail.php?id=253" theid="210"><img
                                    src="http://3gimg.qq.com/daxue_qq_com/image/201707/1500018074911.png"/></div>
                        </a>
                        <a href="javascript:;" class="item">
                            <div title="《王者荣耀》全球版期待你的加入" class="img"
                                 b="https://3gimg.qq.com/daxue_qq_com/image/201801/1517378515836.jpg"
                                 l="https://hr.tencent.com/news_detail.php?id=264" theid="221"><img
                                    src="https://3gimg.qq.com/daxue_qq_com/image/201801/1517378520401.jpg"/></div>
                        </a>
                    </div>
                    <a id="small_next"></a>
                    <div class="clr"></div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block content %}
    <div id="home_cont" class="content">
        <div class="maxwidth">
            {{ message }}
            <div class="left" id="home_l">
                <div class="left" id="home_ll">
                    <form action="{% url 'zhaopin:search' %}">
                        <div id="hsearch1">
                            <input name="keywords" id="hsearch" placeholder="请输入关键词" class="left"
                                   value="{{ keywords }}"/>
                            <input type="submit" id="hshearbut" value="" class="left pointer"/>
                            <div class="clr"></div>
                        </div>
                    </form>
                    <div id="hworkplace">
                        <a href="/search/?lid=0&tid=0&keywords={{ keywords }}">全部</a>
                        {% for workLocation in workLocation_list %}
                            <a href="/search/?lid={{ workLocation.id }}&tid=0&keywords={{ keywords }}">{{ workLocation }}</a>
                        {% endfor %}
                    </div>
                    <br>
                    <div id="hzhiwei">
                        <a href="/search/?lid=0&tid=0&keywords={{ keywords }}">全部</a>
                        {% for category in category_list %}
                            <a href="/search/?lid=0&tid={{ category.id }}&keywords={{ keywords }}">{{ category }}</a>
                        {% endfor %}
                    </div>
                </div>
                <div class="right" id="home_lr" style="padding-top:26px;">
                    <div>
                        <div class="right">
                            <a href="{% url 'zhaopin:social' %}">更多&gt;&gt;</a>
                        </div>
                        <div class="clr"></div>
                    </div>
                    <table id="hhotzw">
                        {% for zhaopin in zhaopin_list %}
                            <tr>
                                <td>
                                    <a href="{% url 'zhaopin:detail' zhaopin.id %}"
                                       title="18797-QQgame移动端高级产品运营(深圳）">{{ zhaopin.title | truncatechars:18 }}</a>
                                </td>
                                <td align="right"><a href="/search/?lid={{ zhaopin.workLocation.id }}&tid=0&keywords=">{{ zhaopin.workLocation }}</a></td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
                <div class="clr"></div>
            </div>
            <div class="right" id="home_r">
                <div id="hnews" style="padding-top:24px;">
                    <div>
                        <div class="right">
                            <a target="_blank" href="https://hr.tencent.com/news.php">更多&gt;&gt;</a>
                        </div>
                        <div class="clr"></div>
                    </div>
                    <div id="hnewsitems" class="square">
                        <a target="_blank" href="https://hr.tencent.com/news_detail.php?id=268" title="MIG2018年春季专场招聘会">MIG2018年春季专场招聘会</a>
                        <a target="_blank" href="https://hr.tencent.com/news_detail.php?id=267" title="腾讯SNG春季技术专场招聘会">腾讯SNG春季技术专场招聘会</a>
                        <a target="_blank" href="https://hr.tencent.com/news_detail.php?id=266" title="腾讯热招AI职位集锦">腾讯热招AI职位集锦</a>
                        <a target="_blank" href="https://hr.tencent.com/news_detail.php?id=265" title="诚邀众俠，仗剑江湖 ">诚邀众俠，仗剑江湖 </a>
                        <a target="_blank" href="https://hr.tencent.com/news_detail.php?id=264" title="《王者荣耀》全球版期待你的加入">《王者荣耀》全球版期待你的加入</a>
                        <a target="_blank" href="https://hr.tencent.com/news_detail.php?id=263" title="欢乐游戏，“职”得拥有">欢乐游戏，“职”得拥有</a>
                        <a target="_blank" href="https://hr.tencent.com/news_detail.php?id=262" title="你是否曾梦想仗剑走天涯？">你是否曾梦想仗剑走天涯？</a>
                        <a target="_blank" href="https://hr.tencent.com/news_detail.php?id=261" title="腾讯新闻：一点知世界">腾讯新闻：一点知世界</a>
                    </div>
                    <div id="dians" class="textr">
                        <a href="javascript:;" num="0" class="dian active">&nbsp;</a>
                        <a href="javascript:;" num="2" class="dian">&nbsp;</a>
                        <a href="javascript:;" num="4" class="dian">&nbsp;</a>
                        <a href="javascript:;" num="6" class="dian">&nbsp;</a>
                    </div>
                    <div class="clr"></div>
                </div>
                <div id="hvideo" onclick="showHomeVideo('x00119isxs3');">
                    <div id="videoshow">
                        <a href="javascript:;"></a>
                    </div>
                </div>
            </div>
            <div class="clr"></div>
        </div>
    </div>
{% endblock %}